#include <stdio.h>
#include <sys/types.h>
#include <emscripten.h>

extern "C" int sched_setaffinity(pid_t, size_t, const struct cpu_set_t *)
{
    return 0;
}

extern "C" int sched_get_priority_max(int)
{
    return 0;
}

extern "C" int sched_get_priority_min(int)
{
    return 10;
}

#include "../JuceLibraryCode/JuceHeader.h"

int pthread_mutexattr_setprotocol(pthread_mutexattr_t *attr, int protocol)
{
    return 0;
}

/*
    The most crappy threading implementation, there ever was.
    Unfortunately, Asyncify did not work for we (compiler crashed).
*/
extern "C" void doThreadIteration(void *(*start_routine) (void *), Thread* thread)
{
    thread->signalThreadShouldExit();
    thread->run();
}


int pthread_create(pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine) (void *), void *arg)
{
    *thread = (pthread_t)EM_ASM_ARGS({
        var doThreadIteration = Module.cwrap('doThreadIteration', 'void', ['number', 'number']);

        var timerId = window.setInterval(function(){
            doThreadIteration($0, $1);
        }, 100);
        return timerId;
    }, start_routine, arg);

    //start_routine(arg);

    return 1; // don't return 0, so that detach is not called
}

int pthread_cancel(pthread_t thread)
{
    EM_ASM_ARGS({
        window.clearInterval($0);
    }, thread);
    return 0;
}

int pthread_setschedparam(pthread_t thread, int policy,
                                 const struct sched_param *param)
{
    return 0;
}

int pthread_getschedparam(pthread_t thread, int *policy,
                                 struct sched_param *param)
{
    return 0;
}


/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "./UI/MainContentComponent.h"




//==============================================================================
class JuceEmscriptenApplication  : public JUCEApplication
{
public:
    //==============================================================================
    JuceEmscriptenApplication()
    {
        std::cout << "VortexSetupApplication::VortexSetupApplication" << std::endl;
    }

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return false; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
        LookAndFeel::setDefaultLookAndFeel(new LookAndFeel_V3());

        mainWindow = new MainWindow ("Untitled - " + getApplicationName());
    }

    void shutdown() override
    {
        // Add your application's shutdown code here..
        std::clog << "!!!!shutdown!!!!" << std::endl;

        mainWindow = nullptr; // (deletes our window)
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

    //==============================================================================
    /*
        This class implements the desktop window that contains an instance of
        our MainContentComponent class.
    */
    class MainWindow    : public DocumentWindow
    {
    public:
        MainWindow (String name)  : DocumentWindow (name,
                                                    Colour(0xff242424),
                                                    DocumentWindow::allButtons)
        {
            std::cout << "MainWindow::MainWindow:" << name << std::endl;

            setUsingNativeTitleBar (false);
            setContentOwned (new MainContentComponent(), true);

            centreWithSize (getWidth(), getHeight());
            setVisible (true);
            setResizable(true, true);
            //560x360
            setResizeLimits(560, 360, 1000000, 1000000);
        }

        void closeButtonPressed() override
        {
            // This is called when the user tries to close this window. Here, we'll just
            // ask the app to quit when this happens, but you can change this to do
            // whatever you need.
            JUCEApplication::getInstance()->systemRequestedQuit();
        }

        /* Note: Be careful if you override any DocumentWindow methods - the base
           class uses a lot of them, so by overriding you might break its functionality.
           It's best to do all your work in your content component instead, but if
           you really have to override any DocumentWindow methods, make sure your
           subclass also calls the superclass's method.
        */

    private:
        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainWindow)
    };

private:
    ScopedPointer<MainWindow> mainWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (JuceEmscriptenApplication)

